# Generated by Django 4.2 on 2024-11-25 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skapp', '0004_house_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='House_details',
            new_name='House_detail',
        ),
    ]
