# Generated by Django 4.2 on 2024-11-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skapp', '0005_rename_house_details_house_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('servuce', models.CharField(max_length=50)),
                ('agent', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
