# Generated by Django 4.2 on 2024-11-26 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skapp', '0006_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='servuce',
            new_name='service',
        ),
    ]
