# Generated by Django 4.2 on 2024-12-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skapp', '0011_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_detail',
            name='area',
            field=models.IntegerField(),
        ),
    ]
